springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    csrf:
      enabled: false  # 스웨거 UI 테스트시 csrf 끄기

jwt:
  secret: ${JWT_SECRET} # 최소 256비트 (32바이트)
  access-token-validity: 900000     # 15분 (단위: ms)
  refresh-token-validity: 604800000 # 7일 (단위: ms)

spring:
  config:
    import: optional:classpath:application-secret.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect